name: Check
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'Documents/**'
      - 'docs/**'
      - '**/*.md'
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
permissions:
  contents: read
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: poetry install --with checks
      - run: poetry run invoke checks
